config/routes.rb
Rails.application.routes.draw do
  scope :module => 'web' do
    root 'tasks#index'

    resources :tasks, only: [:index, :new, :create]

    resources :users, only: [] do
      scope :module => 'users' do
        resources :tasks, except: [:new, :create] do
          member do
            get :download_file
          end
        end
      end
    end

    resources :sessions, only: [:new, :create, :destroy]
    match '/sign_in',  to: 'sessions#new',         via: 'get'
    match '/sign_out', to: 'sessions#destroy',     via: 'delete'
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [] do
      resources :tasks, only: [] do
        member do
          put :next_state
        end
      end
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  include AASM
  belongs_to :user
  validates :name, presence: true
  enum state: {New: 0, Started: 1, Finished: 2}
  mount_uploader :file, FileUploader

  aasm :column => :state, :enum => true do
    state :New, :initial => true
    state :Started
    state :Finished

    event :next_state do
      transitions :from => :New, :to => :Started
      transitions :from => :Started, :to => :Finished
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  before_save { email.downcase! }
  before_create :create_remember_token

  validates :email, presence: true
  validates :password_digest, presence: true
  validates :role, presence: true
  validates :email, uniqueness: { case_sensitive: false }

  enum role: [:user, :admin]

  has_many :tasks, dependent: :destroy

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def admin?
    role == 'admin'
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController; end

app/controllers/api/tasks_controller.rb
class Api::TasksController < Api::ApplicationController
  before_action :find_task, only: :next_state

  def next_state
    if @task.next_state!
      render json: @task.as_json
    else
      render json: @task.as_json
    end
  end

  private

  def find_task
    @task = Task.find_by(id: params[:id])
    return if @task
    render text: t('controllers.api.tasks.fail'), status: 404
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/web/sessions.rb
module Web::Sessions
  include Session

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @tasks = current_user.admin? ? Task.includes(:user) : current_user.tasks
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user_profile_path(user)
    else
      flash[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :json
  before_action :find_task, only: [:show, :edit, :update, :destroy, :download_file, :change_state]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
  end

  def edit
  end

  def create
    @task = Task.create(task_params)

    if @task.persisted?
      redirect_to task_path(@task)
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_path(@task) }
        format.json { render json: {status: '200'}}
      else
        format.html { render 'edit' }
        format.json { render json: {errors: @task.errors, status: '500'} }
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to user_profile_path(current_user)
  end

  def download_file
    if @task.file.present?
      send_file(@task.file.path, :disposition => 'attachment', :url_based_filename => false)
    else
      render text: "Страница не найдена", status: 404
    end
  end

  private
  def task_params
    params.require(:task).permit(:name, :description, :user_id, :state, :file)
  end

  def find_task
    @task = Task.find_by_id(params[:id])
    unless @task
      render text: "Страница не найдена", status: 404
    end
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include Web::Sessions
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user_tasks_path(user)
    else
      flash[:error] = t('controllers.web.sessions.create.flash.error')
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/web/tasks_controller.rb
class Web::TasksController < Web::ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if user_exist? && @task.save
      redirect_to user_task_path(@task.user_id, @task)
    else
      render 'new'
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :user_id,  :file)
  end

  def user_exist?
    User.find(task_params[:user_id]).present?
  end
end

app/controllers/web/users/application_controller.rb
class Web::Users::ApplicationController < Web::ApplicationController; end

app/controllers/web/users/tasks_controller.rb
class Web::Users::TasksController < Web::Users::ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy, :download_file]

  def index
    @tasks = current_user.admin? ? Task.includes(:user) : current_user.tasks
  end

  def show
  end

  def edit
  end

  def update
    if user_exist? && @task.update(task_params)
      redirect_to user_task_path(@task.user, @task)
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to user_tasks_path(current_user)
  end

  def download_file
    if @task.file.present?
      send_file(@task.file.path, disposition: 'attachment', url_based_filename: false)
    else
      render text: t('controllers.web.users.tasks.download_file.fail'), status: 404
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :user_id, :file)
  end

  def find_task
    @task = Task.find_by(id: params[:id])
    return if @task
    render text: t('controllers.web.users.tasks.find_task.fail'), status: 404
  end

  def user_exist?
    User.find(task_params[:user_id]).present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    current_user.admin?
  end

  def show_owner(task)
    task.user.present? ? task.user.email : 'Не назначена'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    return nil unless cookies[:remember_token]
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/web/sessions_helper.rb
module Web::SessionsHelper
  include Session
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Task Manager", root_url, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if signed_in?
          %li
            = link_to "Личный кабинет", user_tasks_path(current_user)
          %li
            = link_to "Выйти", sign_out_path, method: :delete
        - else
          %li
            = link_to "Войти", sign_in_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title TaskManager
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render "layouts/navigation"
    .container.content
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-danger"
      = yield

app/views/shared/_task_form.html.haml
= f.input :name
= f.input :description

- if admin?
  = f.input :user_id, collection: User.all, label_method: :email, value_method: :id, include_blank: false
- else
  = f.input :user_id, :as => :hidden, input_html: { value: current_user.id }

.col-sm-9.col-md-offset-3
  - if task.file.present?
    - if task.file.image?
      .row-fluid
        .col-sm-4
          = image_tag task.file_url, class: "small-image"
        .col-sm-8
          = f.file_field :file, class: "upload-file"
    - else
      %b Прикрепленный файл:
      %span= task.file.get_filename
      = f.file_field :file, class: "upload-file"
  - else
    = f.file_field :file, class: "upload-file"

= f.button :submit, class: "btn pull-right"

app/views/tasks/_form.html.haml
.row
  .col-xs-6.col-md-offset-3
    = simple_form_for task, html: { class: "form-horizontal" }, wrapper: :horizontal_form do |f|
      = f.input :name
      = f.input :description

      - if admin?
        = f.input :user_id, :collection => User.all, :label_method => :email, :value_method => :id, :include_blank => false
      - else
        = f.input :user_id, :as => :hidden, input_html: { value: current_user.id }

      .col-sm-9.col-md-offset-3
        - if task.file.present?
          - if task.file.image?
            .row-fluid
              .col-sm-4
                = image_tag task.file_url, class: "small-image"
              .col-sm-8
                = f.file_field :file, class: "upload-file"
          - else
            %b Прикрепленный файл:
            %span= task.file.get_filename
            = f.file_field :file, class: "upload-file"
        - else
          = f.file_field :file, class: "upload-file"

      = f.button :submit, class: "btn pull-right"

app/views/web/profiles/show.html.haml
.row
  .col-xs-6
    %h1 Личный кабинет

  .create
    = link_to "Cоздать", new_task_path, class: "btn btn-success pull-right"
.row
  - @tasks.each do |task|
    .panel.panel-default
      .panel-heading
        %b= task.name
        .pull-right
          = link_to "Подробнее", task_path(task), class: "btn btn-info btn-xs"
          = link_to "Редактировать", edit_task_path(task), class: "btn btn-warning btn-xs"
          = link_to "Удалить", task_path(task), method: :delete, class: "btn btn-danger btn-xs"
      .panel-body
        %table.table.table-striped.table-hover.table-condensed
          %tbody
            %tr
              %th ID
              %td= task.id
            %tr
              %th Название
              %td= task.name
            %tr
              %th Описание
              %td= task.description
            %tr
              %th Статус
              %td
                .btn-group{"data-toggle" => "buttons"}
                  - ['New', 'Started', 'Finished'].each_with_index do |state, index|
                    %label.btn.btn-primary.btn-xs.state-js{ class: task.state == state ? 'active' : '',
                                                            :'data-task-id' => task.id,
                                                            :'data-task-state' => state}
                      %input{name: "options", type: "radio", id: "option#{index+1}"}
                      = state
            %tr
              %th Создана
              %td= task.created_at
            - if admin?
              %tr
                %th Назначена
                %td= show_owner(task)

app/views/web/tasks/index.html.haml
.row
  .col-lg-12
    %h1 Все задачи
.row
  %table.table.table-striped.table-hover.table-condensed
    %thead
      %tr
        %th ID
        %th Создана
        %th Название
        %th Назначена
    %tbody
      - @tasks.each do |task|
        %tr
          %td
            = task.id
          %td
            = task.created_at
          %td
            = task.name
          %td
            = show_owner(task)

app/views/web/tasks/new.html.haml
%h1.text-center Новая задача
.row
  .col-xs-6.col-md-offset-3
    = simple_form_for @task, html: { class: "form-horizontal" }, wrapper: :horizontal_form do |f|
      = render "shared/task_form", f: f, task: @task

app/views/web/tasks/show.html.haml
%h1 Задача №#{@task.id}
.row
  .panel.panel-default
    .panel-heading
      %b= @task.name
    .panel-body
      %table.table.table-striped.table-hover.table-condensed
        %tbody
          %tr
            %th ID
            %td= @task.id
          %tr
            %th Название
            %td= @task.name
          %tr
            %th Описание
            %td= @task.description
          %tr
            %th Статус
            %td= @task.state
          %tr
            %th Создана
            %td= @task.created_at
          - if admin?
            %tr
              %th Назначена
              %td= show_owner(@task)
          - if @task.file.present?
            %tr
              %th Файл
              %td
                - if @task.file.image?
                  = image_tag @task.file_url, class: "image"
                - else
                  = link_to @task.file.get_filename, download_file_task_path(@task), method: :post

app/views/web/users/tasks/edit.html.haml
%h1.text-center Редактировать задачу


.row
  .col-xs-6.col-md-offset-3
    = simple_form_for @task, url: user_task_path(@task.user, @task), html: { class: "form-horizontal" }, wrapper: :horizontal_form do |f|
      = render "shared/task_form", f: f, task: @task

app/views/web/users/tasks/index.html.haml
.row
  .col-xs-6
    %h1 Личный кабинет

  .create
    = link_to "Cоздать", new_task_path, class: "btn btn-success pull-right"
.row
  - @tasks.each do |task|
    .panel.panel-default
      .panel-heading
        %b= task.name
        .pull-right
          = link_to "Подробнее", user_task_path(task.user, task), class: "btn btn-info btn-xs"
          = link_to "Редактировать", edit_user_task_path(task.user, task), class: "btn btn-warning btn-xs"
          = link_to "Удалить", user_task_path(task.user, task), method: :delete, class: "btn btn-danger btn-xs"
      .panel-body
        %table.table.table-striped.table-hover.table-condensed
          %tbody
            %tr
              %th ID
              %td= task.id
            %tr
              %th Название
              %td= task.name
            %tr
              %th Описание
              %td= task.description
            %tr
              %th Статус
              %td
                %span{id: "state-#{task.id}"}
                  = task.state
                - unless task.Finished?
                  = link_to "Next ->", next_state_api_user_task_path(task.user, task), method: :put, remote: true, class: "btn btn-primary btn-xs pull-right next-state-js"
            %tr
              %th Создана
              %td= task.created_at
            - if admin?
              %tr
                %th Назначена
                %td= show_owner(task)

app/views/web/users/tasks/show.html.haml
%h1 Задача №#{@task.id}
.row
  .panel.panel-default
    .panel-heading
      %b= @task.name
    .panel-body
      %table.table.table-striped.table-hover.table-condensed
        %tbody
          %tr
            %th ID
            %td= @task.id
          %tr
            %th Название
            %td= @task.name
          %tr
            %th Описание
            %td= @task.description
          %tr
            %th Статус
            %td= @task.state
          %tr
            %th Создана
            %td= @task.created_at
          - if admin?
            %tr
              %th Назначена
              %td= show_owner(@task)
          - if @task.file.present?
            %tr
              %th Файл
              %td
                - if @task.file.image?
                  = image_tag @task.file_url, class: "image"
                - else
                  = link_to @task.file.get_filename, download_file_user_task_path(@task.user, @task)